language:
- objective-c
env:
  global:
  #- BUILD_COMMIT=latest-tag  # comment out to build version in submodule
  - REPO_DIR=numpy
  matrix:
  - VERSION=2.7.10
  - VERSION=3.3.5
  - VERSION=3.4.3
  - VERSION=3.5.0
install:
  - source terryfy/travis_tools.sh
  - export CC=clang
  - export CXX=clang++
  - get_python_environment macpython $VERSION venv
  # Update to latest wheel package for Python 3.5
  - pip install -U wheel
  - pip install delocate
  - pip install cython
  - if [ -n "$BUILD_COMMIT" ]; then
        checkout_commit $REPO_DIR $BUILD_COMMIT;
    fi
  - cd $REPO_DIR
  - python setupegg.py bdist_wheel
  - delocate-listdeps dist/*.whl # lists library dependencies
  - delocate-wheel dist/*.whl # copies library dependencies into wheel
  - delocate-addplat --rm-orig -x 10_9 -x 10_10 dist/*.whl
  - pip install dist/*.whl
  - cd ..
script:
  - pip install nose
  - mkdir tmp_test_dir
  - cd tmp_test_dir
  - cd ..
before_deploy:
  - cd $REPO_DIR/dist
  # Fix for https://github.com/travis-ci/travis-ci/issues/4635
  - rvm 1.9.3 do gem install net-ssh -v 2.9.2
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
    secure: "cihGM6hRwKIyd66zGCYLz4S1R1V/ubHEF5CZZ1oWKbO9ztDM/9Gjea2dnMMG7bCHoPMGj5ARMXwpwNnlpZyZgBTuJ/vV9CXKOyoCx+E6oixForAfK2QCikyBQaw7iUZYyM24FFlC4xw92I5sRi8kv6m0YiVCLfVWldmUXEj6nOo="
  region: ORD
  container: wheels
  skip_cleanup: true
