language:
- objective-c
env:
  global:
  - NP_TAG=v1.9.0 # version of numpy to build
  - PACKAGES=numpy
  matrix:
  - VERSION=2.7.8
  - VERSION=3.3.5
  - VERSION=3.4.1
install:
  - cd numpy-atlas-binaries
  - git submodule update --init
  - cd numpy && git fetch --tags && cd ..
  - source travis_install.sh
script:
  - sudo rm -rf /usr/local/gfortran
  - mkdir tmp_test_dir
  - cd tmp_test_dir
  - source ../travis_test.sh
  - cd ../..
before_deploy: cd numpy-atlas-binaries/build/wheelhouse
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
    secure: "cK7eB0yJEINBTB4ZRXON2UxABCcBynX7wwdC1btc9nmAFflEmt4U2h7s4oSiTZZINwDf9iiebMNqD+h0LKG95gSoeCIXoJqy5AWT8uWZy4WBjiEXccoom3qNoddkm9ebkid9srM8gtpclZCZ4C+sIijw2IiyDn/yPy6q9HINVlM="
  region: ORD
  container: wheels
  skip_cleanup: true
