env:
    global:
        - REPO_DIR=numpy
        # Also see CRON_COMMIT below
        - BUILD_COMMIT=6d7b8aaed5ae9f0435764675ebac8c9ada06738f
        - BUILD_DEPENDS=cython==0.29.21
        - TEST_DEPENDS="pytest hypothesis cffi pytz"
        # Commit when running from cron job
        - CRON_COMMIT=master
        - EXTRA_ARGV="'--disable-pytest-warnings'"

language: python
dist: bionic
services: docker
os: linux

jobs:
  include:
    - os: linux
      arch: x86_64
      env:
        - MB_PYTHON_VERSION=pypy3.6-7.3.1
        - MB_ML_VER=2010
        - DOCKER_TEST_IMAGE=multibuild/xenial_{PLAT}

    # The manylinux2014 arm64 image has libbz2.so.1 and libbz.so.1.0.6 but not
    # libbz2.so.1.0, leading to this error with pypy:
    # pypy3.6-v7.3.1-aarch64/bin/pypy: error while loading shared libraries:
    # libbz2.so.1.0: cannot open shared object file: No such file or directory
    #- os: linux
    #  arch: arm64
    #  env:
    #    - PLAT=aarch64
    #    - MB_ML_VER=2014
    #    - MB_PYTHON_VERSION=pypy3.6-7.3.1
    #    - DOCKER_TEST_IMAGE=multibuild/xenial_{PLAT}

    # The pypy3 osx package has bin/pypy3 not bin/pypy, so
    # multibuild/common_utils.sh has a "ln" command (not "ln -s"). Apparently
    # it does not work, we get the error message:
    # multibuild/common_utils.sh: line 476:
    # /Users/travis/build/MacPython/numpy-wheels/pypy3.6-v7.3.1-linux64/bin/pypy:
    # cannot execute binary file
    # - os: osx
    #  language: generic
    #  env:
    #    - MB_PYTHON_VERSION=pypy3.6-7.3.1
    #    - MB_PYTHON_OSX_VER=10.9

    - os: linux
      arch: arm64
      env:
        - PLAT=aarch64
        - MB_ML_VER=2014
        - MB_PYTHON_VERSION=3.6
        - DEBUG_PRINT=1
        - DOCKER_TEST_IMAGE=multibuild/xenial_{PLAT}
    - os: linux
      arch: arm64
      env:
        - PLAT=aarch64
        - MB_ML_VER=2014
        - MB_PYTHON_VERSION=3.7
        - DEBUG_PRINT=1
        - DOCKER_TEST_IMAGE=multibuild/xenial_{PLAT}
    - os: linux
      arch: arm64
      env:
        - PLAT=aarch64
        - MB_ML_VER=2014
        - MB_PYTHON_VERSION=3.8
        - DEBUG_PRINT=1
        - DOCKER_TEST_IMAGE=multibuild/xenial_{PLAT}
    - os: linux
      arch: arm64
      env:
        - PLAT=aarch64
        - MB_ML_VER=2014
        - MB_PYTHON_VERSION=3.9
        - DEBUG_PRINT=1
        - DOCKER_TEST_IMAGE=multibuild/xenial_{PLAT}

before_install:
    - if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then
          CONTAINER="pre-release";
          BUILD_COMMIT=${CRON_COMMIT};
          NPY_RELAXED_STRIDES_DEBUG=1;
      else
          CONTAINER=wheels;
      fi
    # Set DEBUG_PRINT environment variable in settings
    - if [ -n "${DEBUG_PRINT}" ]; then set -x; fi
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - source extra_functions.sh
    - before_install

install:
    # Maybe get and clean and patch source
    - clean_code $REPO_DIR $BUILD_COMMIT
    - ./patch_code.sh $REPO_DIR
    - build_wheel $REPO_DIR $PLAT

script:
    - install_run $PLAT

after_success:
    # trigger an upload to the shared ecosystem
    # infrastructure at: https://anaconda.org/scipy-wheels-nightly
    # for cron jobs only (restricted to master branch once
    # per week)
    # The tokens are set from
    # https://travis-ci.org/github/MacPython/numpy-wheels/settings
    # originally generated at
    # anaconda.org/scipy-wheels-nightly/settings/access
    - if [ "$TRAVIS_BRANCH" == "master" ] ; then
          ANACONDA_ORG="scipy-wheels-nightly";
          TOKEN=${NUMPY_NIGHTLY_UPLOAD_TOKEN};
          source extra_functions.sh;
          for f in wheelhouse/*.whl; do rename_wheel $f; done;
      else
          ANACONDA_ORG="multibuild-wheels-staging";
          TOKEN=${NUMPY_STAGING_UPLOAD_TOKEN};
      fi
    - pip install git+https://github.com/Anaconda-Server/anaconda-client;
    - if [ -n "${TOKEN}" ] ; then
        anaconda -t ${TOKEN} upload -u ${ANACONDA_ORG} ${TRAVIS_BUILD_DIR}/wheelhouse/*.whl;
      fi
