language:
- objective-c
env:
  global:
  - BUILD_COMMIT=v1.9.2  # comment out to build version in submodule
  - REPO_DIR=numpy
  matrix:
  #- VERSION=2.7.9
  #- VERSION=3.3.5
  #- VERSION=3.4.3
  - VERSION=3.5.0
install:
  - source terryfy/travis_tools.sh
  - export CC=clang
  - export CXX=clang++
  - get_python_environment macpython $VERSION venv
  # Install patched version of wheel (patched for 3.5)
  - pip install --ignore-installed --no-index -f https://nipy.bic.berkeley.edu/scipy_installers wheel
  - pip install delocate
  - pip install cython
  - if [ -n "$BUILD_COMMIT" ]; then
        checkout_commit $REPO_DIR $BUILD_COMMIT;
    fi
  - cd $REPO_DIR
  # Cherry-pick Python 3.5 fix
  - if [ "${TRAVIS_PYTHON_VERSION}" == "3.5" ]; then
        git cherry-pick 7d6aa8c;
    fi
  - python setup.py bdist_wheel
  - delocate-listdeps dist/*.whl # lists library dependencies
  - delocate-wheel dist/*.whl # copies library dependencies into wheel
  - delocate-addplat --rm-orig -x 10_9 -x 10_10 dist/*.whl
  - pip install dist/*.whl
  - cd ..
script:
  - pip install nose
  - mkdir tmp_test_dir
  - cd tmp_test_dir
  - python -c "import sys; import numpy; sys.exit(not numpy.test().wasSuccessful())"
  # Set gfortran flags for i386 compile
  - export LDFLAGS="-Wall -undefined dynamic_lookup -bundle -m32"
  - export FARCH='-m32'
  - arch -i386 python -c "import sys; import numpy; sys.exit(not numpy.test().wasSuccessful())"
  # Clean up funny flags after compilation
  - unset LDFLAGS
  - unset FARCH
  - cd ..
before_deploy:
  - cd $REPO_DIR/dist
  # Fix for https://github.com/travis-ci/travis-ci/issues/4635
  - rvm 1.9.3 do gem install net-ssh -v 2.9.2
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
    secure: "cihGM6hRwKIyd66zGCYLz4S1R1V/ubHEF5CZZ1oWKbO9ztDM/9Gjea2dnMMG7bCHoPMGj5ARMXwpwNnlpZyZgBTuJ/vV9CXKOyoCx+E6oixForAfK2QCikyBQaw7iUZYyM24FFlC4xw92I5sRi8kv6m0YiVCLfVWldmUXEj6nOo="
  region: ORD
  container: wheels
  skip_cleanup: true
