language:
- objective-c
env:
  global:
  - NP_COMMIT=latest-tag  # comment out to build version in submodule
  matrix:
  - VERSION=2.7.9
  - VERSION=3.3.5
  - VERSION=3.4.3
install:
  - source terryfy/travis_tools.sh
  - get_python_environment macpython $VERSION venv
  - pip install delocate
  - pip install cython
  - if [ -n "$NP_COMMIT" ]; then
        checkout_commit numpy $NP_COMMIT;
    fi
  - cd numpy
  - python setup.py bdist_wheel
  - delocate-listdeps dist/*.whl # lists library dependencies
  - delocate-wheel dist/*.whl # copies library dependencies into wheel
  - delocate-addplat --rm-orig -x 10_9 -x 10_10 dist/*.whl
  - pip install dist/*.whl
  - cd ..
script:
  - pip install nose
  - mkdir tmp_test_dir
  - cd tmp_test_dir
  - python -c "import sys; import numpy; sys.exit(not numpy.test().wasSuccessful())"
  # Set gfortran flags for i386 compile
  - export LDFLAGS="-Wall -undefined dynamic_lookup -bundle -m32"
  - export FARCH='-m32'
  - arch -i386 python -c "import sys; import numpy; sys.exit(not numpy.test().wasSuccessful())"
  # Clean up funny flags after compilation
  - unset LDFLAGS
  - unset FARCH
  - cd ..
before_deploy: cd numpy/dist
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
    secure: "cihGM6hRwKIyd66zGCYLz4S1R1V/ubHEF5CZZ1oWKbO9ztDM/9Gjea2dnMMG7bCHoPMGj5ARMXwpwNnlpZyZgBTuJ/vV9CXKOyoCx+E6oixForAfK2QCikyBQaw7iUZYyM24FFlC4xw92I5sRi8kv6m0YiVCLfVWldmUXEj6nOo="
  region: ORD
  container: wheels
  skip_cleanup: true
